# Generated by Django 6.0.3 on 2026-03-21 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, unique=True)),
                ('ioc_type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('hash', 'File Hash')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IOCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc', models.CharField(max_length=255)),
                ('ioc_type', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('link', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IOCAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('verdict', models.CharField(max_length=50)),
                ('mitre', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='dashboard.ioc')),
            ],
        ),
        migrations.CreateModel(
            name='IOCSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('raw_data', models.JSONField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='dashboard.iocanalysis')),
            ],
        ),
    ]
